# Generated by Django 2.2.16 on 2023-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsceneword',
            name='word',
            field=models.CharField(error_messages={'unique': 'Такое слово уже есть.'}, max_length=25, unique=True, verbose_name='Запрещенное слово'),
        ),
    ]
