# Generated by Django 2.2.16 on 2023-02-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230221_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obsceneword',
            options={'ordering': ('word',), 'verbose_name': 'Запрещенное слово', 'verbose_name_plural': 'Запрещенные слова'},
        ),
    ]
