# Generated by Django 2.2.6 on 2023-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230119_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsceneWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, verbose_name='Запрещенное слово')),
            ],
            options={
                'verbose_name': 'Запрещенное слово',
                'verbose_name_plural': 'Запрещенные слова',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
