# Generated by Django 2.2.6 on 2023-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230208_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObsceneWord',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
